# Generated by Django 4.2.1 on 2023-05-27 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_profile_image"),
        ("posts", "0003_remove_post_user_post_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="user_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="profiles.profile",
            ),
        ),
    ]
