# Generated by Django 4.2.1 on 2023-05-31 07:46

from django.db import migrations
from django.db.migrations import RunPython


def func(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "fixture_data.json")


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_alter_like_user_profile_alter_post_user_profile_and_more"),
    ]

    operations = [
        RunPython(func, reverse_func)
    ]
