# Generated by Django 4.2.1 on 2023-05-26 06:19

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_profile_follows"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                null=True, upload_to=profiles.models.profile_image_file_path
            ),
        ),
    ]
